% compile_propagation.m

disp('compiling/installing dijkstraset_mex...')
mex -I./ -I./fheap ...
    fheap/fib.cpp ...
    dijkstraset_mex.cpp ...
    -output dijkstraset_mex
eval(['!move dijkstraset_mex.' mexext ' ../']);

disp('compiling/installing dijkstrapropagation_mex...')
mex -largeArrayDims -I./ -I./fheap ...
    fheap/fib.cpp ...
    dijkstrapropagation_mex.cpp ...
    -output dijkstrapropagation_mex
eval(['!move dijkstrapropagation_mex.' mexext ' ../']);

disp('compiling/installing fmmpropagation_mex...')
mex -I./ -I./fheap ...
    fheap/fib.cpp ...
    fmmisopropagation_2d.cpp ...
    fmmisopropagation_mex.cpp ...
    -output fmmisopropagation_mex
eval(['!move fmmisopropagation_mex.' mexext ' ../']);

disp('compiling/installing fm2daniso_mex...')
mex -I./ -I./fheap ...
    fheap/fib.cpp ...
    fm2daniso_mex.cpp ...
    -output fm2daniso_mex
eval(['!move fm2daniso_mex.' mexext ' ../']);

disp('compiling/installing fmmanisopropagation_mex...')
mex -I./ -I./GCM ...
    fmmanisopropagation_mex.cpp ...
    -output fmmanisopropagation_mex
eval(['!move fmmanisopropagation_mex.' mexext ' ../']);

